In [5]:
import pandas as pd
import os

In [6]:
df_list_misc = []


for root, dirs, files in os.walk('Match-Reports'):
    for file in files:
        if file.endswith('.pkl'):
            file_path = os.path.join(root, file)
            df = pd.read_pickle(file_path)

df

,date,home_team,away_team,home_score,away_score,referee
0,2021-08-13,Brentford,Arsenal,2,0,Michael Oliver
1,2021-08-14,Manchester United,Leeds United,5,1,Paul Tierney
2,2021-08-14,Leicester City,Wolverhampton Wanderers,1,0,Craig Pawson
3,2021-08-14,Burnley,Brighton & Hove Albion,1,2,David Coote
4,2021-08-14,Chelsea,Crystal Palace,3,0,Jonathan Moss
...,...,...,...,...,...,...
375,2022-05-22,Norwich City,Tottenham Hotspur,0,5,Chris Kavanagh
376,2022-05-22,Manchester City,Aston Villa,3,2,Michael Oliver
377,2022-05-22,Liverpool,Wolverhampton Wanderers,3,1,Anthony Taylor
378,2022-05-22,Burnley,Newcastle United,1,2,Craig Pawson
379,2022-05-22,Chelsea,Watford,2,1,Mike Dean